name: Auto-publish
on:
  rss:
    url: https://journal.robbi.my/index.xml
    config:
      logLevel: debug
      limit: 1
jobs:
  publish_twitter:
    name: publish on github
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
     
      - name: "Github"
        run: |
          curl -i \
          -d source=${{on.rss.outputs.link}} \
          -d target=https://brid.gy/publish/github?bridgy_omit_link=false \
          https://brid.gy/publish/webmention
